config/routes.rb
Rails.application.routes.draw do

    #顧客
  # URL /customers/sign_in ...
  devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  root to: "public/homes#top"
  get 'about' => 'public/homes#about'


  get '/genre/search' => 'searches#genre_search'

  scope module: :public do
    get "customers/my_page" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    resources :addresses, only: [:index, :create, :destroy, :edit, :update]
    #退会確認画面
    get '/customers/confirm' => 'customers#confirm'
    #退会処理
    patch '/customers/withdrawal' => 'customers#withdrawal'
  end

  scope module: :public do
    resources :items, only: [:index, :show]
  end

  scope module: :public do
    resources :cart_items, only: [:index, :create, :update, :destroy]
  end

  delete 'cart_items/destroy_all' => 'public/cart_items#destroy_all'

  scope module: :public do
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :create, :index, :show]
  end


  # 管理者
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

    get 'admin' => 'admin/homes#top'

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end

    namespace :admin do
    resources :orders, only: [:show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
    super && (is_deleted == false)
  end

  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy


  
  #validates :address, format: { with: /\A\d{7}\z/ }
  #validates :telephone_number, format: { with: /\A\d{10,11}\z/ }
  #validates :first_name, /^[ぁ-んァ-ヶー一-龠]+$/

  


end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
    def index
        @customers = Customer.all.page(params[:page])
    end

    def show
        @customer = Customer.find(params[:id])
        @customers = Customer.all.page(params[:page])
    end

    def edit
        @customer = Customer.find(params[:id])
    end

    def update
        @customer = Customer.find(params[:id])
        @customer.update(customer_params)
        flash[:notice] = "会員情報を編集しました"
        redirect_to admin_customer_path
    end

    private
    def customer_params
        params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :zip_code, :address, :telephone_number, :email, :is_deleted)
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container p-5">
  <div class="row mb-3">
      <h4 style="background-color: #dcdcdc;">　<%= @customer.first_name + @customer.last_name %>さんの会員情報編集　</h4>
  </div>
  
  
  <%= form_with model: @customer, url: admin_customer_path(@customer.id), local: :true, method: :put do |f| %>
    <div class="row">
        <label class="col-lg-2">会員ID</label>
        <div class="col-lg-3">
          <%= @customer.id %>
        </div>
    </div>

    <div class="row">
      <label class="col-lg-2">氏名</label>
      <div class="col-lg-3">
        <%= f.text_field :first_name,autoforcus: true %>
      </div>
      <div class="col-lg-3">
        <%= f.text_field :last_name,autoforcus: true %>
      </div>
    </div><br>

    <div class="row my-1">
      <label class="col-lg-2">フリガナ</label>
      <div class="col-lg-3">
        <%= f.text_field :first_name_kana %>
      </div>
      <div class="col-lg-3">
        <%= f.text_field :last_name_kana%>
      </div>
    </div><br>

    <div class="row">
      <label class="col-lg-2">郵便番号</label>
      <div class="col-lg-3">
        <%= f.text_field :zip_code %>
      </div>
    </div><br>

    <div class="row my-1">
      <label class="col-lg-2">住所</label>
      <div class="col-lg-3">
        <%= f.text_field :address %>
      </div>
    </div><br>

    <div class="row">
      <label class="col-lg-2">電話番号</label>
      <div class="col-lg-3">
        <%= f.text_field :telephone_number %>
      </div>
    </div><br>

    <div class="row mt-1 mb-3">
      <label class="col-lg-2">メールアドレス</label>
      <div class="col-lg-3">
        <%= f.text_field :email %>
      </div>
    </div>
    <div class="row mb-5">
      <div class="col-lg-2">
        <%= f.label :"会員ステータス" %>
      </div>
      <div class="col-lg-3">
        <%= f.radio_button :is_deleted, :false %>
        <%= f.label :is_deleted, "有効" %>
        <%= f.radio_button :is_deleted, :true %>
        <%= f.label :is_deleted, "退会" %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-2"></div>
      <div class="col-lg-3">
        <%= f.submit "　変更内容を保存　", class:"btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row my-3 ml-5">
    <h4 style="background-color: #dcdcdc;">　会員一覧　</h4>
  </div>

  <div class="row">
    <div class="col-sm-10 px-sm-0 offset-sm-1">
      <table class="table">
        <thead>
          <tr bgcolor="#dcdcdc">
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td><%= link_to customer.first_name + customer.last_name, admin_customer_path(customer.id) %></td>
          <td><%= customer.email %></td>
          <td class="<%= customer.is_deleted ? 'text-black-50' : 'text-success' %>"><strong><%= customer.is_deleted ? '退会' : '有効' %></strong></td>
        </tr>
        <% end %>
      </table>
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container p-5">
  <div class="row">
      <h4 style="background-color: #dcdcdc;"><%= @customer.first_name + @customer.last_name %>さんの会員詳細</h4>
  </div>
  <div class="row">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <table class="table table-borderless">
        <tr>
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td><%= @customer.first_name + @customer.last_name %></td>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td><%= @customer.first_name_kana + @customer.last_name_kana %></td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= @customer.zip_code %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
            <% if @customer.is_deleted == false %>
              <td class="text-success font-weight-bold"><strong>有効</strong></td>
            <% else %>
              <td class="text-secondary"><strong>退会</strong></td>
            <% end %>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="mx-auto">
      <%= link_to "編集する", edit_admin_customer_path(@customer.id), class:"btn btn-success" %>
      　　　<%= link_to "注文履歴一覧をみる", admin_path, class: "btn btn-primary" %>
    </div>
  </div>
  <%= paginate @customers %>
</div>