config/routes.rb
Rails.application.routes.draw do

    #顧客
  # URL /customers/sign_in ...
  devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  root to: "public/homes#top"
  get 'about' => 'public/homes#about'


  get '/genre/search' => 'searches#genre_search'

  scope module: :public do
    get "customers/my_page" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    resources :addresses, only: [:index, :create, :destroy, :edit, :update]
    #退会確認画面
    get '/customers/confirm' => 'customers#confirm'
    #退会処理
    patch '/customers/withdrawal' => 'customers#withdrawal'
  end

  scope module: :public do
    resources :items, only: [:index, :show]
  end

  scope module: :public do
    resources :cart_items, only: [:index, :create, :update, :destroy]
  end

  delete 'cart_items/destroy_all' => 'public/cart_items#destroy_all'

  scope module: :public do
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :create, :index, :show]
  end


  # 管理者
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

    get 'admin' => 'admin/homes#top'

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end

    namespace :admin do
    resources :orders, only: [:show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  VALID_POSTCODE_REGEX = /\A\d{7}$\z/

  belongs_to :customer

  def address_and_zip_code_and_name
    "〒#{self.address}  #{self.zip_code}  #{self.name}"
  end

  validates :address, presence: true, format: { with: VALID_POSTCODE_REGEX }
  validates :zip_code, presence: true, length: { in: 1..48 }
  validates :name, presence: true, length: { in: 1..32 }

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord


  belongs_to :customer
  belongs_to :item

  def subtotal
    item.add_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
    super && (is_deleted == false)
  end

  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy


  
  #validates :address, format: { with: /\A\d{7}\z/ }
  #validates :telephone_number, format: { with: /\A\d{10,11}\z/ }
  #validates :first_name, /^[ぁ-んァ-ヶー一-龠]+$/

  


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  belongs_to :genre
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  def  add_tax_price
    (price * 1.10).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
        if request.referer == new_admin_item_url
          flash[:notice] = "ジャンルの作成に成功しました"
          redirect_to request.referer
        else
          redirect_to admin_genres_path
        end
    else
     @genres = Genre.all
     render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @order = Order.all
    @orders = Order.all.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_item, only: %i[show edit update]

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save

      redirect_to admin_item_path(@item.id),notice: "商品を登録しました。"
    else
      @genres = Genre.all

      render :new
    end
  end



  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end



  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id), notice: "商品情報を更新しました。"
    else
      @genres = Genre.all
      render :edit
    end
  end

  def set_item
    @item = Item.find(params[:id])
  end

  private

  def item_params
    params.require(:item).permit(:name, :explanation, :price, :image, :is_active, :genre_id)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  
  def show
    @order = Order.find(params[:id])
    @customer = Customer.find(params[:id])
    @order_details = @order.order_details
  end

  def update
  @order = Order.find(params[:id])
  @order_details = OrderDetail.where(order_id: params[:id])
  if @order.update(order_params)
    @order_details.update_all(maiking_status: 1) if @order.status == "payment_confirmation"
  end
    redirect_to admin_order_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource)
    admin_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container py-5">
  <div class="row mb-3 ml-5">
    <div class="col-3">
      <h1 style="background-color: #dcdcdc;">ジャンル編集</h1>
    </div>
  </div>

  <div class="row mb-5">
    <div class="col-7">
      <%= form_with model: @genre, url: admin_genre_path, method: :patch do |f| %>
      <tr>
        <td><%= f.label :"ジャンル名", class: "mr-3" %></td>
        <td><%= f.text_field :name, class: "mr-5" %></td>
        <td><%= f.submit'変更を保存', class: "btn btn-primary" %></td>
      </tr>
      <% end %>
    </div>
  </div>

app/views/admin/genres/index.html.erb
<div class="container p-5 mb-5">
  <div class="row mb-5 ml-5">
    <h4 style="background-color: #dcdcdc;">ジャンル一覧・追加</h4>
  </div>

  <div class="row mb-4">
    <%= form_with model: @genre,url: admin_genres_path, method: :post do |f| %>
      <td><%= f.label :"ジャンル名", class: "mr-3" %></td>
      <td><%= f.text_field :name, class: "mr-5" %></td>
      <td><%= f.submit'新規登録', class: "btn btn-success" %></td>
    <% end %>
  </div>
  

  <div class="row">
    <div class="col-lg-5 mt-3">
      <table class="table">
       
        <tr bgcolor="#dcdcdc">
          <th>　　ジャンル</th>
          <th></th>
        </tr>
        
        <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.name %></td>
            <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-sm btn-success" %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container p-5">
  <div class="row mb-5">
    <h4 style="background-color: #dcdcdc;">　商品編集　</h4>
  </div>
  
   <div class="container">
    <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>

      <div class="row justify-content-center mb-2">
        <label class="col-2">商品画像</label>
        <div class="col-4">
          <%= f.file_field :image, accept: "image/*" %>
        </div>
      </div>

      <div class="row justify-content-center mb-2">
        <label class="col-2">商品名</label>
        <div class="col-4">
          <%= f.text_field :name, placeholder: "商品名", size: "26" %>
        </div>
      </div>

      <div class="row justify-content-center mb-2">
        <label class="col-2">商品説明</label>
        <div class="col-4">
          <%= f.text_area :explanation, placeholder: "ここに説明を記述します", size:"30x6" %>
        </div>
      </div>

      <div class="row justify-content-center mb-2">
        <label class="col-2">ジャンル</label>
        <div class="col-4">
          選択ボックス<%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"mentor-skill"}) %>
        </div>
      </div>

      <div class="row justify-content-center mb-2">
        <label class="col-2">税抜価格</label>
        <div class="col-4">
          <%= f.text_field :price, placeholder: "1000", size: "26" %>
        </div>
      </div>

      <div class="row justify-content-center mb-4">
        <label class="col-2">販売ステータス</label>
        <div class="col-4">
          
          <%= f.radio_button :is_active, :true %>
          <%= f.label :is_active_true, "販売中" %>
          
          <%= f.radio_button :is_active, :false %>
          <%= f.label :is_active_false, "販売停止中" %>
        </div>
      </div>

      <div class="row mb-5">
        <%= f.submit "変更を保存", class: "btn btn-success mx-auto" %>
      </div>

    <% end %>
</div>

app/views/admin/items/index.html.erb
<div class="container p-5">
  <div class="row mb-3">
    <h4 style="background-color: #dcdcdc;">　商品一覧　</h4>

    <%= link_to "＋", new_admin_item_path, class: "btn rounded-circle  ml-auto shadow  p-2" %>
  </div>
  <table class="table table-borderless table-hover">

    <thead>
      <tr bgcolor="#dcdcdc">
        <th>商品ID</th>
        <th style="width: 30%">商品名</th>
        <th>税抜価格</th>
        <th style="width: 30%">ジャンル</th>
        <th style="width: 20%">ステータス</th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td>
          <%= link_to admin_item_path(item.id) do %>
            <%= item.name %>
          <% end %>
        </td>
        <td><%= item.price.to_s(:delimited) %></td>
        <td><%= item.genre.name %></td>
        <td>
          <% if item.is_active == true %>
            <div class="text-success">
              販売中
            </div>
          <% else %>
            <div class="text-danger">
              販売停止中
            </div>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>

  </table>

  <div class="row">
    <div class="mx-auto">
      <%= paginate @items %>
    </div>
  </div>

</div>

app/views/admin/items/new.html.erb
<div class="container p-5">

  <div class="row mb-3">
    <h4 class="bg-secondary">　商品新規登録　</h4>
  </div>

  <div class="container">
    <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>

      <div class="row justify-content-center mb-2">
        <label class="col-2">商品画像</label>
        <div class="col-4">
          <%= f.file_field :image, accept: "image/*" %>
        </div>
      </div>

      <div class="row justify-content-center mb-2">
        <label class="col-2">商品名</label>
        <div class="col-4">
          <%= f.text_field :name, placeholder: "商品名", size: "26" %>
        </div>
      </div>

      <div class="row justify-content-center mb-2">
        <label class="col-2">商品説明</label>
        <div class="col-4">
          <%= f.text_area :explanation, placeholder: "ここに説明を記述します", size:"30x6" %>
        </div>
      </div>

      <div class="row justify-content-center mb-2">
        <label class="col-2">ジャンル</label>
        <div class="col-4">
          選択ボックス<%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"mentor-skill"}) %>
        </div>
      </div>

      <div class="row justify-content-center mb-2">
        <label class="col-2">税抜価格</label>
        <div class="col-4">
          <%= f.text_field :price, placeholder: "1000", size: "26" %>
        </div>
      </div>

      <div class="row justify-content-center mb-4">
        <label class="col-2">販売ステータス</label>
        <div class="col-4">

          <%= f.radio_button :is_active, :true %>
          <%= f.label :is_active_true, "販売中" %>

          <%= f.radio_button :is_active, :false %>
          <%= f.label :is_active_false, "販売停止中" %>
        </div>
      </div>

      <div class="row mb-5">
        <%= f.submit "新規登録", class: "btn btn-success mx-auto" %>
      </div>

    <% end %>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container p-5">
  <div class="row ml-3 mb-5">

    <h4 style="background-color: #dcdcdc;">　商品詳細　</h4>

  </div>

  <div class="row justify-content-center">
    <div class="col-4">
        <%= image_tag @item.image, size: "250x200" %>
    </div>

    <div class="col-7">
      <table class="table table-borderless">
        <tr>
          <td style="width: 30%">商品名</td>
          <td><%= @item.name %></td>
        </tr>

        <tr>
          <td>商品説明</td>
          <td><%= @item.explanation %></td>
        </tr>

        <tr>
          <td>ジャンル</td>
          <td><%= @item.genre.name %></td>
        </tr>

        <tr>
          <td>
            税込価格<br>
          (税抜価格)
          </td>
          <td>
            <%= @item.add_tax_price.to_s(:delimited) %>
          (<%= @item.price.to_s(:delimited) %>)　円
          </td>
        </tr>

        <tr>
          <td>販売ステータス</td>
          <td>
            <% if @item.is_active == true %>
              <div class="text-success">
                <strong>販売中</strong>
              </div>
            <% else %>
              <div class="text-danger">
                <strong>販売停止中</strong>
              </div>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>

  <div class="row my-3">
    <%= link_to "　編集する　", edit_admin_item_path(@item.id), class: "btn btn-success mx-auto" %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container p-3">

  <div class="row">
    <h4 style="background-color: #dcdcdc;">注文履歴詳細</h4>
  </div>

  <div class="row mt-1">
    <div class="col-md-12">
      <table class="text-left" style="font-size: 15pt" >

        <tr>
          <th><strong>購入者</strong></th>
          <th>
            <%= link_to admin_customer_path(@customer.id) do %>
              <%= @order.customer.last_name + @order.customer.first_name %>
            <% end %>
          </th>
        </tr>

        <tr>
          <th><strong>注文日</strong></th>
          <th><%= @order.customer.created_at.strftime('%Y/%m/%d') %></th>
        </tr>

        <tr>
          <th><strong>配送先</strong></th>
          <th>〒<%= @order.customer.zip_code + " " + @order.customer.address + " " + @order.customer.last_name + " " + @order.customer.first_name %></th>
        </tr>

        <tr>
          <th><strong>支払方法</strong></th>
          <th><%= @order.payment_method_i18n %></th>
        </tr>

        <tr>

          <th><strong>注文ステータス</strong></th>
          <th>
            <%= form_with model: @order, url: admin_order_path, method: :get, local: true do |f| %>
              <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %>
              <%= f.submit "更新" , class: "btn btn-success" %>
            <% end %>
          </th>
        </tr>
      </table>
    </div>
  </div>

  <div class ="row mt-2">
    <div class="col-md-8">
      <table class="table">
        <thead>
          <tr bgcolor="#dcdcdc">
            <th style="width: 25%">商品名</th>
            <th style="width: 15%">単価(税込)</th>
            <th style="width: 15%">数量</th>
            <th style="width: 15%">小計</th>
            <th style="width: 30%">製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
          <tr>
            <th><%= order_detail.item.name %></th>
            <th><%= order_detail.item.add_tax_price.to_s(:delimited) %></th>
            <th><%= order_detail.amount %></th>
            <th><%= order_detail.item.add_tax_price.to_s(:delimited) * order_detail.amount %></th>
            <th>
              <%= form_with model: @order_detail, url: admin_order_path, method: :get, local: true do |f| %>
                <%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
                <%= f.submit "更新" , class: "btn btn-success" %>
              <% end %>
            </th>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-4">
      <table calss="table" style="font-size: 15pt">
        <tr>
          <th><strong>商品合計</strong></th>
          <th><%= @order.total_payment - @order.postage %></th>
        </tr>

        <tr>
          <th><strong>送料</strong></th>
          <th><%= @order.postage %></th>
        </tr>

        <tr>
          <th><strong>請求金額合計</strong></th>
          <th><strong><%= @order.total_payment %></strong></th>
        </tr>
      </table>
    </div>
  </div>
</div>