config/routes.rb
Rails.application.routes.draw do

    #顧客
  # URL /customers/sign_in ...
  devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  root to: "public/homes#top"
  get 'about' => 'public/homes#about'


  get '/genre/search' => 'searches#genre_search'

  scope module: :public do
    get "customers/my_page" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    resources :addresses, only: [:index, :create, :destroy, :edit, :update]
    #退会確認画面
    get '/customers/confirm' => 'customers#confirm'
    #退会処理
    patch '/customers/withdrawal' => 'customers#withdrawal'
  end

  scope module: :public do
    resources :items, only: [:index, :show]
  end

  scope module: :public do
    resources :cart_items, only: [:index, :create, :update, :destroy]
  end

  delete 'cart_items/destroy_all' => 'public/cart_items#destroy_all'

  scope module: :public do
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :create, :index, :show]
  end


  # 管理者
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

    get 'admin' => 'admin/homes#top'

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end

    namespace :admin do
    resources :orders, only: [:show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  VALID_POSTCODE_REGEX = /\A\d{7}$\z/

  belongs_to :customer

  def address_and_zip_code_and_name
    "〒#{self.address}  #{self.zip_code}  #{self.name}"
  end

  validates :address, presence: true, format: { with: VALID_POSTCODE_REGEX }
  validates :zip_code, presence: true, length: { in: 1..48 }
  validates :name, presence: true, length: { in: 1..32 }

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord


  belongs_to :customer
  belongs_to :item

  def subtotal
    item.add_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
    super && (is_deleted == false)
  end

  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy


  
  #validates :address, format: { with: /\A\d{7}\z/ }
  #validates :telephone_number, format: { with: /\A\d{10,11}\z/ }
  #validates :first_name, /^[ぁ-んァ-ヶー一-龠]+$/

  


end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  belongs_to :genre
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  def  add_tax_price
    (price * 1.10).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
        if request.referer == new_admin_item_url
          flash[:notice] = "ジャンルの作成に成功しました"
          redirect_to request.referer
        else
          redirect_to admin_genres_path
        end
    else
     @genres = Genre.all
     render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @order = Order.all
    @orders = Order.all.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_item, only: %i[show edit update]

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save

      redirect_to admin_item_path(@item.id),notice: "商品を登録しました。"
    else
      @genres = Genre.all

      render :new
    end
  end



  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end



  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id), notice: "商品情報を更新しました。"
    else
      @genres = Genre.all
      render :edit
    end
  end

  def set_item
    @item = Item.find(params[:id])
  end

  private

  def item_params
    params.require(:item).permit(:name, :explanation, :price, :image, :is_active, :genre_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer class="border-top">
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>nagano-cake</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/f253770af7.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar-fixed-top">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('no_image.jpg') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <!-- adminヘッダー -->
              <% if admin_signed_in? %>
              <li class="nav-item">
                <%= link_to admin_items_path do %>
                  <i class="fa-solid fa-cake-candles">商品一覧</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_customers_path do %>
                  <i class="fa-solid fa-users">会員一覧</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_path  do %>
                  <i class="fas fa-clipboard-list">注文履歴一覧</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_genres_path do%>
                  <i class="fas fa-tags">ジャンル一覧</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_admin_session_path, method: :delete do %>
                  <i class="fas fa-sign-out-alt">ログアウト</i>
                <% end %>
              </li>
              <li class="mt-auto">
                <div class="input-group">
                  <input type="text" id="txt-search" class="form-control input-group-prepend" placeholder="Search"></input>
                    <submit type="submit" id="btn-search" class="btn btn-primary"><i class="fas fa-search"></i></submit>
                </div>
              </li>


              <!--customersログイン時のヘッダー-->
            <% elsif customer_signed_in? %>
              <li class="nav-item">
                ようこそ<%= link_to customers_confirm_path do %>
                <%= current_customer.first_name %>さん
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to customers_my_page_path do %>
                  <i class="fas fa-user-circle">マイページ</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to  items_path do %>
                  <i class="fa-solid fa-cake-candles">商品一覧</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to cart_items_path do %>
                  <i class="fas fa-shopping-cart">カート</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_customer_session_path, method: :delete do %>
                  <i class="fas fa-sign-out-alt">ログアウト</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= text_field_tag :search %>
                <%= submit_tag 'Search', :name => nil %>
              </li>


              <% else %>
              <!--ログイン前のヘッダー-->
              <li class="nav-item">
                <%= link_to about_path do %>
                  <i class="fa-solid fa-eject">About</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to items_path do %>
                  <i class="fa-solid fa-cake-candles">商品一覧</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_customer_registration_path, data: {"turbolinks" => false} do %>
                  <i class="fas fa-user-plus">新規登録</i>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to  new_customer_session_path do%>
                  <i class="fas fa-user">ログイン</i>
                <% end %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    </div>
    <main class"mb-auto">
    <%= yield %>
    </main>

    <footer>
      <%= render "layouts/footer" %>
    </footer>
  </body>
</html>